/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package geometry_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgeometry_msgs__rosidl_typesupport_c -lgeometry_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <geometry_msgs/msg/pose.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("geometry_msgs/Pose", PoseTypeSupport)
}

// Do not create instances of this type directly. Always use NewPose
// function instead.
type Pose struct {
	Position Point `yaml:"position"`
	Orientation Quaternion `yaml:"orientation"`
}

// NewPose creates a new Pose with default values.
func NewPose() *Pose {
	self := Pose{}
	self.SetDefaults()
	return &self
}

func (t *Pose) Clone() *Pose {
	c := &Pose{}
	c.Position = *t.Position.Clone()
	c.Orientation = *t.Orientation.Clone()
	return c
}

func (t *Pose) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Pose) SetDefaults() {
	t.Position.SetDefaults()
	t.Orientation.SetDefaults()
}

// ClonePoseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func ClonePoseSlice(dst, src []Pose) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var PoseTypeSupport types.MessageTypeSupport = _PoseTypeSupport{}

type _PoseTypeSupport struct{}

func (t _PoseTypeSupport) New() types.Message {
	return NewPose()
}

func (t _PoseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.geometry_msgs__msg__Pose
	return (unsafe.Pointer)(C.geometry_msgs__msg__Pose__create())
}

func (t _PoseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.geometry_msgs__msg__Pose__destroy((*C.geometry_msgs__msg__Pose)(pointer_to_free))
}

func (t _PoseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Pose)
	mem := (*C.geometry_msgs__msg__Pose)(dst)
	PointTypeSupport.AsCStruct(unsafe.Pointer(&mem.position), &m.Position)
	QuaternionTypeSupport.AsCStruct(unsafe.Pointer(&mem.orientation), &m.Orientation)
}

func (t _PoseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Pose)
	mem := (*C.geometry_msgs__msg__Pose)(ros2_message_buffer)
	PointTypeSupport.AsGoStruct(&m.Position, unsafe.Pointer(&mem.position))
	QuaternionTypeSupport.AsGoStruct(&m.Orientation, unsafe.Pointer(&mem.orientation))
}

func (t _PoseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__geometry_msgs__msg__Pose())
}

type CPose = C.geometry_msgs__msg__Pose
type CPose__Sequence = C.geometry_msgs__msg__Pose__Sequence

func Pose__Sequence_to_Go(goSlice *[]Pose, cSlice CPose__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Pose, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.geometry_msgs__msg__Pose__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_geometry_msgs__msg__Pose * uintptr(i)),
		))
		PoseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func Pose__Sequence_to_C(cSlice *CPose__Sequence, goSlice []Pose) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.geometry_msgs__msg__Pose)(C.malloc((C.size_t)(C.sizeof_struct_geometry_msgs__msg__Pose * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.geometry_msgs__msg__Pose)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_geometry_msgs__msg__Pose * uintptr(i)),
		))
		PoseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func Pose__Array_to_Go(goSlice []Pose, cSlice []CPose) {
	for i := 0; i < len(cSlice); i++ {
		PoseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Pose__Array_to_C(cSlice []CPose, goSlice []Pose) {
	for i := 0; i < len(goSlice); i++ {
		PoseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
