/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package example_interfaces_srv

/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lexample_interfaces__rosidl_typesupport_c -lexample_interfaces__rosidl_generator_c
#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>
#include <example_interfaces/srv/add_two_ints.h>
*/
import "C"

import (
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"

	"unsafe"
)

func init() {
	typemap.RegisterService("example_interfaces/AddTwoInts", AddTwoIntsTypeSupport)
}

type _AddTwoIntsTypeSupport struct {}

func (s _AddTwoIntsTypeSupport) Request() types.MessageTypeSupport {
	return AddTwoInts_RequestTypeSupport
}

func (s _AddTwoIntsTypeSupport) Response() types.MessageTypeSupport {
	return AddTwoInts_ResponseTypeSupport
}

func (s _AddTwoIntsTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__example_interfaces__srv__AddTwoInts())
}

// Modifying this variable is undefined behavior.
var AddTwoIntsTypeSupport types.ServiceTypeSupport = _AddTwoIntsTypeSupport{}
