/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package rcl_interfaces
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/ros2/ros2types"
	"github.com/tiiuae/rclgo/pkg/ros2/ros2_type_dispatcher"
	rosidl_runtime_c "github.com/tiiuae/rclgo/pkg/ros2/rosidl_runtime_c"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lrcl_interfaces__rosidl_typesupport_c -lrcl_interfaces__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rcl_interfaces/msg/list_parameters_result.h>
*/
import "C"

func init() {
	ros2_type_dispatcher.RegisterROS2MsgTypeNameAlias("rcl_interfaces/ListParametersResult", &ListParametersResult{})
}

// Do not create instances of this type directly. Always use NewListParametersResult
// function instead.
type ListParametersResult struct {
	Names []rosidl_runtime_c.String `yaml:"names"`// The resulting parameters under the given prefixes.
	Prefixes []rosidl_runtime_c.String `yaml:"prefixes"`// The resulting prefixes under the given prefixes.TODO(wjwwood): link to prefix definition and rules.
}

// NewListParametersResult creates a new ListParametersResult with default values.
func NewListParametersResult() *ListParametersResult {
	self := ListParametersResult{}
	self.SetDefaults(nil)
	return &self
}

func (t *ListParametersResult) SetDefaults(d interface{}) ros2types.ROS2Msg {
	
	return t
}

func (t *ListParametersResult) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rcl_interfaces__msg__ListParametersResult())
}
func (t *ListParametersResult) PrepareMemory() unsafe.Pointer { //returns *C.rcl_interfaces__msg__ListParametersResult
	return (unsafe.Pointer)(C.rcl_interfaces__msg__ListParametersResult__create())
}
func (t *ListParametersResult) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rcl_interfaces__msg__ListParametersResult__destroy((*C.rcl_interfaces__msg__ListParametersResult)(pointer_to_free))
}
func (t *ListParametersResult) AsCStruct() unsafe.Pointer {
	mem := (*C.rcl_interfaces__msg__ListParametersResult)(t.PrepareMemory())
	rosidl_runtime_c.String__Sequence_to_C((*rosidl_runtime_c.CString__Sequence)(unsafe.Pointer(&mem.names)), t.Names)
	rosidl_runtime_c.String__Sequence_to_C((*rosidl_runtime_c.CString__Sequence)(unsafe.Pointer(&mem.prefixes)), t.Prefixes)
	return unsafe.Pointer(mem)
}
func (t *ListParametersResult) AsGoStruct(ros2_message_buffer unsafe.Pointer) {
	mem := (*C.rcl_interfaces__msg__ListParametersResult)(ros2_message_buffer)
	rosidl_runtime_c.String__Sequence_to_Go(&t.Names, *(*rosidl_runtime_c.CString__Sequence)(unsafe.Pointer(&mem.names)))
	rosidl_runtime_c.String__Sequence_to_Go(&t.Prefixes, *(*rosidl_runtime_c.CString__Sequence)(unsafe.Pointer(&mem.prefixes)))
}
func (t *ListParametersResult) Clone() ros2types.ROS2Msg {
	clone := *t
	return &clone
}

type CListParametersResult = C.rcl_interfaces__msg__ListParametersResult
type CListParametersResult__Sequence = C.rcl_interfaces__msg__ListParametersResult__Sequence

func ListParametersResult__Sequence_to_Go(goSlice *[]ListParametersResult, cSlice CListParametersResult__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ListParametersResult, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.rcl_interfaces__msg__ListParametersResult__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_rcl_interfaces__msg__ListParametersResult * uintptr(i)),
		))
		(*goSlice)[i] = ListParametersResult{}
		(*goSlice)[i].AsGoStruct(unsafe.Pointer(cIdx))
	}
}
func ListParametersResult__Sequence_to_C(cSlice *CListParametersResult__Sequence, goSlice []ListParametersResult) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.rcl_interfaces__msg__ListParametersResult)(C.malloc((C.size_t)(C.sizeof_struct_rcl_interfaces__msg__ListParametersResult * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.rcl_interfaces__msg__ListParametersResult)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_rcl_interfaces__msg__ListParametersResult * uintptr(i)),
		))
		*cIdx = *(*C.rcl_interfaces__msg__ListParametersResult)(v.AsCStruct())
	}
}
func ListParametersResult__Array_to_Go(goSlice []ListParametersResult, cSlice []CListParametersResult) {
	for i := 0; i < len(cSlice); i++ {
		goSlice[i].AsGoStruct(unsafe.Pointer(&cSlice[i]))
	}
}
func ListParametersResult__Array_to_C(cSlice []CListParametersResult, goSlice []ListParametersResult) {
	for i := 0; i < len(goSlice); i++ {
		cSlice[i] = *(*C.rcl_interfaces__msg__ListParametersResult)(goSlice[i].AsCStruct())
	}
}


