/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package map_msgs_srv

/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lmap_msgs__rosidl_typesupport_c -lmap_msgs__rosidl_generator_c
#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>
#include <map_msgs/srv/set_map_projections.h>
*/
import "C"

import (
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"

	"unsafe"
)

func init() {
	typemap.RegisterService("map_msgs/SetMapProjections", SetMapProjectionsTypeSupport)
}

type _SetMapProjectionsTypeSupport struct {}

func (s _SetMapProjectionsTypeSupport) Request() types.MessageTypeSupport {
	return SetMapProjections_RequestTypeSupport
}

func (s _SetMapProjectionsTypeSupport) Response() types.MessageTypeSupport {
	return SetMapProjections_ResponseTypeSupport
}

func (s _SetMapProjectionsTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__map_msgs__srv__SetMapProjections())
}

// Modifying this variable is undefined behavior.
var SetMapProjectionsTypeSupport types.ServiceTypeSupport = _SetMapProjectionsTypeSupport{}
