/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package tf2_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -ltf2_msgs__rosidl_typesupport_c -ltf2_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <tf2_msgs/srv/frame_graph.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("tf2_msgs/FrameGraph_Response", FrameGraph_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewFrameGraph_Response
// function instead.
type FrameGraph_Response struct {
	FrameYaml string `yaml:"frame_yaml"`
}

// NewFrameGraph_Response creates a new FrameGraph_Response with default values.
func NewFrameGraph_Response() *FrameGraph_Response {
	self := FrameGraph_Response{}
	self.SetDefaults()
	return &self
}

func (t *FrameGraph_Response) Clone() types.Message {
	clone := *t
	return &clone
}

func (t *FrameGraph_Response) SetDefaults() {
	
}

// Modifying this variable is undefined behavior.
var FrameGraph_ResponseTypeSupport types.MessageTypeSupport = _FrameGraph_ResponseTypeSupport{}

type _FrameGraph_ResponseTypeSupport struct{}

func (t _FrameGraph_ResponseTypeSupport) New() types.Message {
	return NewFrameGraph_Response()
}

func (t _FrameGraph_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.tf2_msgs__srv__FrameGraph_Response
	return (unsafe.Pointer)(C.tf2_msgs__srv__FrameGraph_Response__create())
}

func (t _FrameGraph_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.tf2_msgs__srv__FrameGraph_Response__destroy((*C.tf2_msgs__srv__FrameGraph_Response)(pointer_to_free))
}

func (t _FrameGraph_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*FrameGraph_Response)
	mem := (*C.tf2_msgs__srv__FrameGraph_Response)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.frame_yaml), m.FrameYaml)
}

func (t _FrameGraph_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*FrameGraph_Response)
	mem := (*C.tf2_msgs__srv__FrameGraph_Response)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.FrameYaml, unsafe.Pointer(&mem.frame_yaml))
}

func (t _FrameGraph_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__tf2_msgs__srv__FrameGraph_Response())
}

type CFrameGraph_Response = C.tf2_msgs__srv__FrameGraph_Response
type CFrameGraph_Response__Sequence = C.tf2_msgs__srv__FrameGraph_Response__Sequence

func FrameGraph_Response__Sequence_to_Go(goSlice *[]FrameGraph_Response, cSlice CFrameGraph_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]FrameGraph_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.tf2_msgs__srv__FrameGraph_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_tf2_msgs__srv__FrameGraph_Response * uintptr(i)),
		))
		FrameGraph_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func FrameGraph_Response__Sequence_to_C(cSlice *CFrameGraph_Response__Sequence, goSlice []FrameGraph_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.tf2_msgs__srv__FrameGraph_Response)(C.malloc((C.size_t)(C.sizeof_struct_tf2_msgs__srv__FrameGraph_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.tf2_msgs__srv__FrameGraph_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_tf2_msgs__srv__FrameGraph_Response * uintptr(i)),
		))
		FrameGraph_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func FrameGraph_Response__Array_to_Go(goSlice []FrameGraph_Response, cSlice []CFrameGraph_Response) {
	for i := 0; i < len(cSlice); i++ {
		FrameGraph_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func FrameGraph_Response__Array_to_C(cSlice []CFrameGraph_Response, goSlice []FrameGraph_Response) {
	for i := 0; i < len(goSlice); i++ {
		FrameGraph_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
