/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package diagnostic_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/ros2/ros2types"
	"github.com/tiiuae/rclgo/pkg/ros2/ros2_type_dispatcher"
	rosidl_runtime_c "github.com/tiiuae/rclgo/pkg/ros2/rosidl_runtime_c"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -ldiagnostic_msgs__rosidl_typesupport_c -ldiagnostic_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <diagnostic_msgs/msg/key_value.h>

*/
import "C"

func init() {
	ros2_type_dispatcher.RegisterROS2MsgTypeNameAlias("diagnostic_msgs/KeyValue", &KeyValue{})
}

// Do not create instances of this type directly. Always use NewKeyValue
// function instead.
type KeyValue struct {
	Key rosidl_runtime_c.String `yaml:"key"`// What to label this value when viewing.
	Value rosidl_runtime_c.String `yaml:"value"`// What to label this value when viewing.A value to track over time.
}

// NewKeyValue creates a new KeyValue with default values.
func NewKeyValue() *KeyValue {
	self := KeyValue{}
	self.SetDefaults(nil)
	return &self
}

func (t *KeyValue) SetDefaults(d interface{}) ros2types.ROS2Msg {
	t.Key.SetDefaults("")
	t.Value.SetDefaults("")
	
	return t
}

func (t *KeyValue) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__diagnostic_msgs__msg__KeyValue())
}
func (t *KeyValue) PrepareMemory() unsafe.Pointer { //returns *C.diagnostic_msgs__msg__KeyValue
	return (unsafe.Pointer)(C.diagnostic_msgs__msg__KeyValue__create())
}
func (t *KeyValue) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.diagnostic_msgs__msg__KeyValue__destroy((*C.diagnostic_msgs__msg__KeyValue)(pointer_to_free))
}
func (t *KeyValue) AsCStruct() unsafe.Pointer {
	mem := (*C.diagnostic_msgs__msg__KeyValue)(t.PrepareMemory())
	mem.key = *(*C.rosidl_runtime_c__String)(t.Key.AsCStruct())
	mem.value = *(*C.rosidl_runtime_c__String)(t.Value.AsCStruct())
	return unsafe.Pointer(mem)
}
func (t *KeyValue) AsGoStruct(ros2_message_buffer unsafe.Pointer) {
	mem := (*C.diagnostic_msgs__msg__KeyValue)(ros2_message_buffer)
	t.Key.AsGoStruct(unsafe.Pointer(&mem.key))
	t.Value.AsGoStruct(unsafe.Pointer(&mem.value))
}
func (t *KeyValue) Clone() ros2types.ROS2Msg {
	clone := *t
	return &clone
}

type CKeyValue = C.diagnostic_msgs__msg__KeyValue
type CKeyValue__Sequence = C.diagnostic_msgs__msg__KeyValue__Sequence

func KeyValue__Sequence_to_Go(goSlice *[]KeyValue, cSlice CKeyValue__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]KeyValue, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.diagnostic_msgs__msg__KeyValue__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_diagnostic_msgs__msg__KeyValue * uintptr(i)),
		))
		(*goSlice)[i] = KeyValue{}
		(*goSlice)[i].AsGoStruct(unsafe.Pointer(cIdx))
	}
}
func KeyValue__Sequence_to_C(cSlice *CKeyValue__Sequence, goSlice []KeyValue) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.diagnostic_msgs__msg__KeyValue)(C.malloc((C.size_t)(C.sizeof_struct_diagnostic_msgs__msg__KeyValue * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.diagnostic_msgs__msg__KeyValue)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_diagnostic_msgs__msg__KeyValue * uintptr(i)),
		))
		*cIdx = *(*C.diagnostic_msgs__msg__KeyValue)(v.AsCStruct())
	}
}
func KeyValue__Array_to_Go(goSlice []KeyValue, cSlice []CKeyValue) {
	for i := 0; i < len(cSlice); i++ {
		goSlice[i].AsGoStruct(unsafe.Pointer(&cSlice[i]))
	}
}
func KeyValue__Array_to_C(cSlice []CKeyValue, goSlice []KeyValue) {
	for i := 0; i < len(goSlice); i++ {
		cSlice[i] = *(*C.diagnostic_msgs__msg__KeyValue)(goSlice[i].AsCStruct())
	}
}


