/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package rmw_dds_common_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lrmw_dds_common__rosidl_typesupport_c -lrmw_dds_common__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rmw_dds_common/msg/gid.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rmw_dds_common/Gid", GidTypeSupport)
}

// Do not create instances of this type directly. Always use NewGid
// function instead.
type Gid struct {
	Data [24]byte `yaml:"data"`
}

// NewGid creates a new Gid with default values.
func NewGid() *Gid {
	self := Gid{}
	self.SetDefaults()
	return &self
}

func (t *Gid) Clone() types.Message {
	clone := *t
	return &clone
}

func (t *Gid) SetDefaults() {
	
}

// Modifying this variable is undefined behavior.
var GidTypeSupport types.MessageTypeSupport = _GidTypeSupport{}

type _GidTypeSupport struct{}

func (t _GidTypeSupport) New() types.Message {
	return NewGid()
}

func (t _GidTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rmw_dds_common__msg__Gid
	return (unsafe.Pointer)(C.rmw_dds_common__msg__Gid__create())
}

func (t _GidTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rmw_dds_common__msg__Gid__destroy((*C.rmw_dds_common__msg__Gid)(pointer_to_free))
}

func (t _GidTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Gid)
	mem := (*C.rmw_dds_common__msg__Gid)(dst)
	cSlice_data := mem.data[:]
	primitives.Char__Array_to_C(*(*[]primitives.CChar)(unsafe.Pointer(&cSlice_data)), m.Data[:])
}

func (t _GidTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Gid)
	mem := (*C.rmw_dds_common__msg__Gid)(ros2_message_buffer)
	cSlice_data := mem.data[:]
	primitives.Char__Array_to_Go(m.Data[:], *(*[]primitives.CChar)(unsafe.Pointer(&cSlice_data)))
}

func (t _GidTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rmw_dds_common__msg__Gid())
}

type CGid = C.rmw_dds_common__msg__Gid
type CGid__Sequence = C.rmw_dds_common__msg__Gid__Sequence

func Gid__Sequence_to_Go(goSlice *[]Gid, cSlice CGid__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Gid, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.rmw_dds_common__msg__Gid__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_rmw_dds_common__msg__Gid * uintptr(i)),
		))
		GidTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func Gid__Sequence_to_C(cSlice *CGid__Sequence, goSlice []Gid) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.rmw_dds_common__msg__Gid)(C.malloc((C.size_t)(C.sizeof_struct_rmw_dds_common__msg__Gid * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.rmw_dds_common__msg__Gid)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_rmw_dds_common__msg__Gid * uintptr(i)),
		))
		GidTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func Gid__Array_to_Go(goSlice []Gid, cSlice []CGid) {
	for i := 0; i < len(cSlice); i++ {
		GidTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Gid__Array_to_C(cSlice []CGid, goSlice []Gid) {
	for i := 0; i < len(goSlice); i++ {
		GidTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
