/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package sensor_msgs
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/ros2/ros2types"
	"github.com/tiiuae/rclgo/pkg/ros2/ros2_type_dispatcher"
	std_msgs "github.com/tiiuae/rclgo/pkg/ros2/msgs/std_msgs/msg"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lsensor_msgs__rosidl_typesupport_c -lsensor_msgs__rosidl_generator_c
#cgo LDFLAGS: -lstd_msgs__rosidl_typesupport_c -lstd_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>
#include <sensor_msgs/msg/relative_humidity.h>
*/
import "C"

func init() {
	ros2_type_dispatcher.RegisterROS2MsgTypeNameAlias("sensor_msgs/RelativeHumidity", &RelativeHumidity{})
}

// Do not create instances of this type directly. Always use NewRelativeHumidity
// function instead.
type RelativeHumidity struct {
	Header std_msgs.Header `yaml:"header"`// timestamp of the measurement
	RelativeHumidity float64 `yaml:"relative_humidity"`// Expression of the relative humidity
	Variance float64 `yaml:"variance"`// 0 is interpreted as variance unknown
}

// NewRelativeHumidity creates a new RelativeHumidity with default values.
func NewRelativeHumidity() *RelativeHumidity {
	self := RelativeHumidity{}
	self.SetDefaults(nil)
	return &self
}

func (t *RelativeHumidity) SetDefaults(d interface{}) ros2types.ROS2Msg {
	t.Header.SetDefaults(nil)
	
	return t
}

func (t *RelativeHumidity) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__sensor_msgs__msg__RelativeHumidity())
}
func (t *RelativeHumidity) PrepareMemory() unsafe.Pointer { //returns *C.sensor_msgs__msg__RelativeHumidity
	return (unsafe.Pointer)(C.sensor_msgs__msg__RelativeHumidity__create())
}
func (t *RelativeHumidity) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.sensor_msgs__msg__RelativeHumidity__destroy((*C.sensor_msgs__msg__RelativeHumidity)(pointer_to_free))
}
func (t *RelativeHumidity) AsCStruct() unsafe.Pointer {
	mem := (*C.sensor_msgs__msg__RelativeHumidity)(t.PrepareMemory())
	mem.header = *(*C.std_msgs__msg__Header)(t.Header.AsCStruct())
	mem.relative_humidity = C.double(t.RelativeHumidity)
	mem.variance = C.double(t.Variance)
	return unsafe.Pointer(mem)
}
func (t *RelativeHumidity) AsGoStruct(ros2_message_buffer unsafe.Pointer) {
	mem := (*C.sensor_msgs__msg__RelativeHumidity)(ros2_message_buffer)
	t.Header.AsGoStruct(unsafe.Pointer(&mem.header))
	t.RelativeHumidity = float64(mem.relative_humidity)
	t.Variance = float64(mem.variance)
}
func (t *RelativeHumidity) Clone() ros2types.ROS2Msg {
	clone := *t
	return &clone
}

type CRelativeHumidity = C.sensor_msgs__msg__RelativeHumidity
type CRelativeHumidity__Sequence = C.sensor_msgs__msg__RelativeHumidity__Sequence

func RelativeHumidity__Sequence_to_Go(goSlice *[]RelativeHumidity, cSlice CRelativeHumidity__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]RelativeHumidity, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.sensor_msgs__msg__RelativeHumidity__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_sensor_msgs__msg__RelativeHumidity * uintptr(i)),
		))
		(*goSlice)[i] = RelativeHumidity{}
		(*goSlice)[i].AsGoStruct(unsafe.Pointer(cIdx))
	}
}
func RelativeHumidity__Sequence_to_C(cSlice *CRelativeHumidity__Sequence, goSlice []RelativeHumidity) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.sensor_msgs__msg__RelativeHumidity)(C.malloc((C.size_t)(C.sizeof_struct_sensor_msgs__msg__RelativeHumidity * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.sensor_msgs__msg__RelativeHumidity)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_sensor_msgs__msg__RelativeHumidity * uintptr(i)),
		))
		*cIdx = *(*C.sensor_msgs__msg__RelativeHumidity)(v.AsCStruct())
	}
}
func RelativeHumidity__Array_to_Go(goSlice []RelativeHumidity, cSlice []CRelativeHumidity) {
	for i := 0; i < len(cSlice); i++ {
		goSlice[i].AsGoStruct(unsafe.Pointer(&cSlice[i]))
	}
}
func RelativeHumidity__Array_to_C(cSlice []CRelativeHumidity, goSlice []RelativeHumidity) {
	for i := 0; i < len(goSlice); i++ {
		cSlice[i] = *(*C.sensor_msgs__msg__RelativeHumidity)(goSlice[i].AsCStruct())
	}
}


