/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package sensor_msgs
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/ros2/ros2types"
	"github.com/tiiuae/rclgo/pkg/ros2/ros2_type_dispatcher"
	std_msgs "github.com/tiiuae/rclgo/pkg/ros2/msgs/std_msgs/msg"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lsensor_msgs__rosidl_typesupport_c -lsensor_msgs__rosidl_generator_c
#cgo LDFLAGS: -lstd_msgs__rosidl_typesupport_c -lstd_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>
#include <sensor_msgs/msg/temperature.h>
*/
import "C"

func init() {
	ros2_type_dispatcher.RegisterROS2MsgTypeNameAlias("sensor_msgs/Temperature", &Temperature{})
}

// Do not create instances of this type directly. Always use NewTemperature
// function instead.
type Temperature struct {
	Header std_msgs.Header `yaml:"header"`// timestamp is the time the temperature was measured
	Temperature float64 `yaml:"temperature"`// Measurement of the Temperature in Degrees Celsius.
	Variance float64 `yaml:"variance"`// 0 is interpreted as variance unknown.
}

// NewTemperature creates a new Temperature with default values.
func NewTemperature() *Temperature {
	self := Temperature{}
	self.SetDefaults(nil)
	return &self
}

func (t *Temperature) SetDefaults(d interface{}) ros2types.ROS2Msg {
	t.Header.SetDefaults(nil)
	
	return t
}

func (t *Temperature) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__sensor_msgs__msg__Temperature())
}
func (t *Temperature) PrepareMemory() unsafe.Pointer { //returns *C.sensor_msgs__msg__Temperature
	return (unsafe.Pointer)(C.sensor_msgs__msg__Temperature__create())
}
func (t *Temperature) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.sensor_msgs__msg__Temperature__destroy((*C.sensor_msgs__msg__Temperature)(pointer_to_free))
}
func (t *Temperature) AsCStruct() unsafe.Pointer {
	mem := (*C.sensor_msgs__msg__Temperature)(t.PrepareMemory())
	mem.header = *(*C.std_msgs__msg__Header)(t.Header.AsCStruct())
	mem.temperature = C.double(t.Temperature)
	mem.variance = C.double(t.Variance)
	return unsafe.Pointer(mem)
}
func (t *Temperature) AsGoStruct(ros2_message_buffer unsafe.Pointer) {
	mem := (*C.sensor_msgs__msg__Temperature)(ros2_message_buffer)
	t.Header.AsGoStruct(unsafe.Pointer(&mem.header))
	t.Temperature = float64(mem.temperature)
	t.Variance = float64(mem.variance)
}
func (t *Temperature) Clone() ros2types.ROS2Msg {
	clone := *t
	return &clone
}

type CTemperature = C.sensor_msgs__msg__Temperature
type CTemperature__Sequence = C.sensor_msgs__msg__Temperature__Sequence

func Temperature__Sequence_to_Go(goSlice *[]Temperature, cSlice CTemperature__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Temperature, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.sensor_msgs__msg__Temperature__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_sensor_msgs__msg__Temperature * uintptr(i)),
		))
		(*goSlice)[i] = Temperature{}
		(*goSlice)[i].AsGoStruct(unsafe.Pointer(cIdx))
	}
}
func Temperature__Sequence_to_C(cSlice *CTemperature__Sequence, goSlice []Temperature) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.sensor_msgs__msg__Temperature)(C.malloc((C.size_t)(C.sizeof_struct_sensor_msgs__msg__Temperature * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.sensor_msgs__msg__Temperature)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_sensor_msgs__msg__Temperature * uintptr(i)),
		))
		*cIdx = *(*C.sensor_msgs__msg__Temperature)(v.AsCStruct())
	}
}
func Temperature__Array_to_Go(goSlice []Temperature, cSlice []CTemperature) {
	for i := 0; i < len(cSlice); i++ {
		goSlice[i].AsGoStruct(unsafe.Pointer(&cSlice[i]))
	}
}
func Temperature__Array_to_C(cSlice []CTemperature, goSlice []Temperature) {
	for i := 0; i < len(goSlice); i++ {
		cSlice[i] = *(*C.sensor_msgs__msg__Temperature)(goSlice[i].AsCStruct())
	}
}


