/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package rcl_interfaces_srv

/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lrcl_interfaces__rosidl_typesupport_c -lrcl_interfaces__rosidl_generator_c
#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>
#include <rcl_interfaces/srv/list_parameters.h>
*/
import "C"

import (
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"

	"unsafe"
)

func init() {
	typemap.RegisterService("rcl_interfaces/ListParameters", ListParametersTypeSupport)
}

type _ListParametersTypeSupport struct {}

func (s _ListParametersTypeSupport) Request() types.MessageTypeSupport {
	return ListParameters_RequestTypeSupport
}

func (s _ListParametersTypeSupport) Response() types.MessageTypeSupport {
	return ListParameters_ResponseTypeSupport
}

func (s _ListParametersTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__rcl_interfaces__srv__ListParameters())
}

// Modifying this variable is undefined behavior.
var ListParametersTypeSupport types.ServiceTypeSupport = _ListParametersTypeSupport{}
