/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package fog_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/ros2/ros2types"
	"github.com/tiiuae/rclgo/pkg/ros2/ros2_type_dispatcher"
	nav_msgs_msg "github.com/tiiuae/rclgo/pkg/ros2/msgs/nav_msgs/msg"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lfog_msgs__rosidl_typesupport_c -lfog_msgs__rosidl_generator_c
#cgo LDFLAGS: -lnav_msgs__rosidl_typesupport_c -lnav_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <fog_msgs/srv/path.h>

*/
import "C"

func init() {
	ros2_type_dispatcher.RegisterROS2MsgTypeNameAlias("fog_msgs/Path_Request", &Path_Request{})
}

// Do not create instances of this type directly. Always use NewPath_Request
// function instead.
type Path_Request struct {
	Path nav_msgs_msg.Path `yaml:"path"`
}

// NewPath_Request creates a new Path_Request with default values.
func NewPath_Request() *Path_Request {
	self := Path_Request{}
	self.SetDefaults(nil)
	return &self
}

func (t *Path_Request) SetDefaults(d interface{}) ros2types.ROS2Msg {
	t.Path.SetDefaults(nil)
	
	return t
}

func (t *Path_Request) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__fog_msgs__srv__Path_Request())
}
func (t *Path_Request) PrepareMemory() unsafe.Pointer { //returns *C.fog_msgs__srv__Path_Request
	return (unsafe.Pointer)(C.fog_msgs__srv__Path_Request__create())
}
func (t *Path_Request) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.fog_msgs__srv__Path_Request__destroy((*C.fog_msgs__srv__Path_Request)(pointer_to_free))
}
func (t *Path_Request) AsCStruct() unsafe.Pointer {
	mem := (*C.fog_msgs__srv__Path_Request)(t.PrepareMemory())
	mem.path = *(*C.nav_msgs__msg__Path)(t.Path.AsCStruct())
	return unsafe.Pointer(mem)
}
func (t *Path_Request) AsGoStruct(ros2_message_buffer unsafe.Pointer) {
	mem := (*C.fog_msgs__srv__Path_Request)(ros2_message_buffer)
	t.Path.AsGoStruct(unsafe.Pointer(&mem.path))
}
func (t *Path_Request) Clone() ros2types.ROS2Msg {
	clone := *t
	return &clone
}

type CPath_Request = C.fog_msgs__srv__Path_Request
type CPath_Request__Sequence = C.fog_msgs__srv__Path_Request__Sequence

func Path_Request__Sequence_to_Go(goSlice *[]Path_Request, cSlice CPath_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Path_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.fog_msgs__srv__Path_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_fog_msgs__srv__Path_Request * uintptr(i)),
		))
		(*goSlice)[i] = Path_Request{}
		(*goSlice)[i].AsGoStruct(unsafe.Pointer(cIdx))
	}
}
func Path_Request__Sequence_to_C(cSlice *CPath_Request__Sequence, goSlice []Path_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.fog_msgs__srv__Path_Request)(C.malloc((C.size_t)(C.sizeof_struct_fog_msgs__srv__Path_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.fog_msgs__srv__Path_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_fog_msgs__srv__Path_Request * uintptr(i)),
		))
		*cIdx = *(*C.fog_msgs__srv__Path_Request)(v.AsCStruct())
	}
}
func Path_Request__Array_to_Go(goSlice []Path_Request, cSlice []CPath_Request) {
	for i := 0; i < len(cSlice); i++ {
		goSlice[i].AsGoStruct(unsafe.Pointer(&cSlice[i]))
	}
}
func Path_Request__Array_to_C(cSlice []CPath_Request, goSlice []Path_Request) {
	for i := 0; i < len(goSlice); i++ {
		cSlice[i] = *(*C.fog_msgs__srv__Path_Request)(goSlice[i].AsCStruct())
	}
}


