/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package px4_msgs
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/ros2/ros2types"
	"github.com/tiiuae/rclgo/pkg/ros2/ros2_type_dispatcher"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lpx4_msgs__rosidl_typesupport_c -lpx4_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>
#include <px4_msgs/msg/debug_value.h>
*/
import "C"

func init() {
	ros2_type_dispatcher.RegisterROS2MsgTypeNameAlias("px4_msgs/DebugValue", &DebugValue{})
}

// Do not create instances of this type directly. Always use NewDebugValue
// function instead.
type DebugValue struct {
	Timestamp uint64 `yaml:"timestamp"`// time since system start (microseconds)
	Ind int8 `yaml:"ind"`// index of debug variable
	Value float32 `yaml:"value"`// the value to send as debug output
}

// NewDebugValue creates a new DebugValue with default values.
func NewDebugValue() *DebugValue {
	self := DebugValue{}
	self.SetDefaults(nil)
	return &self
}

func (t *DebugValue) SetDefaults(d interface{}) ros2types.ROS2Msg {
	
	return t
}

func (t *DebugValue) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__px4_msgs__msg__DebugValue())
}
func (t *DebugValue) PrepareMemory() unsafe.Pointer { //returns *C.px4_msgs__msg__DebugValue
	return (unsafe.Pointer)(C.px4_msgs__msg__DebugValue__create())
}
func (t *DebugValue) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.px4_msgs__msg__DebugValue__destroy((*C.px4_msgs__msg__DebugValue)(pointer_to_free))
}
func (t *DebugValue) AsCStruct() unsafe.Pointer {
	mem := (*C.px4_msgs__msg__DebugValue)(t.PrepareMemory())
	mem.timestamp = C.uint64_t(t.Timestamp)
	mem.ind = C.int8_t(t.Ind)
	mem.value = C.float(t.Value)
	return unsafe.Pointer(mem)
}
func (t *DebugValue) AsGoStruct(ros2_message_buffer unsafe.Pointer) {
	mem := (*C.px4_msgs__msg__DebugValue)(ros2_message_buffer)
	t.Timestamp = uint64(mem.timestamp)
	t.Ind = int8(mem.ind)
	t.Value = float32(mem.value)
}
func (t *DebugValue) Clone() ros2types.ROS2Msg {
	clone := *t
	return &clone
}

type CDebugValue = C.px4_msgs__msg__DebugValue
type CDebugValue__Sequence = C.px4_msgs__msg__DebugValue__Sequence

func DebugValue__Sequence_to_Go(goSlice *[]DebugValue, cSlice CDebugValue__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]DebugValue, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.px4_msgs__msg__DebugValue__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_px4_msgs__msg__DebugValue * uintptr(i)),
		))
		(*goSlice)[i] = DebugValue{}
		(*goSlice)[i].AsGoStruct(unsafe.Pointer(cIdx))
	}
}
func DebugValue__Sequence_to_C(cSlice *CDebugValue__Sequence, goSlice []DebugValue) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.px4_msgs__msg__DebugValue)(C.malloc((C.size_t)(C.sizeof_struct_px4_msgs__msg__DebugValue * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.px4_msgs__msg__DebugValue)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_px4_msgs__msg__DebugValue * uintptr(i)),
		))
		*cIdx = *(*C.px4_msgs__msg__DebugValue)(v.AsCStruct())
	}
}
func DebugValue__Array_to_Go(goSlice []DebugValue, cSlice []CDebugValue) {
	for i := 0; i < len(cSlice); i++ {
		goSlice[i].AsGoStruct(unsafe.Pointer(&cSlice[i]))
	}
}
func DebugValue__Array_to_C(cSlice []CDebugValue, goSlice []DebugValue) {
	for i := 0; i < len(goSlice); i++ {
		cSlice[i] = *(*C.px4_msgs__msg__DebugValue)(goSlice[i].AsCStruct())
	}
}


