/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package px4_msgs
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/ros2/ros2types"
	"github.com/tiiuae/rclgo/pkg/ros2/ros2_type_dispatcher"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lpx4_msgs__rosidl_typesupport_c -lpx4_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>
#include <px4_msgs/msg/esc_status.h>
*/
import "C"

func init() {
	ros2_type_dispatcher.RegisterROS2MsgTypeNameAlias("px4_msgs/EscStatus", &EscStatus{})
}
const (
	EscStatus_CONNECTED_ESC_MAX uint8 = 8// The number of ESCs supported. Current (Q2/2013) we support 8 ESCs
	EscStatus_ESC_CONNECTION_TYPE_PPM uint8 = 0// Traditional PPM ESC
	EscStatus_ESC_CONNECTION_TYPE_SERIAL uint8 = 1// Serial Bus connected ESC
	EscStatus_ESC_CONNECTION_TYPE_ONESHOT uint8 = 2// One Shot PPM
	EscStatus_ESC_CONNECTION_TYPE_I2C uint8 = 3// I2C
	EscStatus_ESC_CONNECTION_TYPE_CAN uint8 = 4// CAN-Bus
	EscStatus_ESC_CONNECTION_TYPE_DSHOT uint8 = 5// DShot
)

// Do not create instances of this type directly. Always use NewEscStatus
// function instead.
type EscStatus struct {
	Timestamp uint64 `yaml:"timestamp"`// time since system start (microseconds)
	Counter uint16 `yaml:"counter"`// incremented by the writing thread everytime new data is stored
	EscCount uint8 `yaml:"esc_count"`// number of connected ESCs
	EscConnectiontype uint8 `yaml:"esc_connectiontype"`// how ESCs connected to the system
	EscOnlineFlags uint8 `yaml:"esc_online_flags"`// Bitmask indicating which ESC is online/offline
	EscArmedFlags uint8 `yaml:"esc_armed_flags"`// Bitmask indicating which ESC is armed. For ESC's where the arming state is not known (returned by the ESC), the arming bits should always be set.
	Esc [8]EscReport `yaml:"esc"`
}

// NewEscStatus creates a new EscStatus with default values.
func NewEscStatus() *EscStatus {
	self := EscStatus{}
	self.SetDefaults(nil)
	return &self
}

func (t *EscStatus) SetDefaults(d interface{}) ros2types.ROS2Msg {
	t.Esc[0].SetDefaults(nil)
	t.Esc[1].SetDefaults(nil)
	t.Esc[2].SetDefaults(nil)
	t.Esc[3].SetDefaults(nil)
	t.Esc[4].SetDefaults(nil)
	t.Esc[5].SetDefaults(nil)
	t.Esc[6].SetDefaults(nil)
	t.Esc[7].SetDefaults(nil)
	
	return t
}

func (t *EscStatus) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__px4_msgs__msg__EscStatus())
}
func (t *EscStatus) PrepareMemory() unsafe.Pointer { //returns *C.px4_msgs__msg__EscStatus
	return (unsafe.Pointer)(C.px4_msgs__msg__EscStatus__create())
}
func (t *EscStatus) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.px4_msgs__msg__EscStatus__destroy((*C.px4_msgs__msg__EscStatus)(pointer_to_free))
}
func (t *EscStatus) AsCStruct() unsafe.Pointer {
	mem := (*C.px4_msgs__msg__EscStatus)(t.PrepareMemory())
	mem.timestamp = C.uint64_t(t.Timestamp)
	mem.counter = C.uint16_t(t.Counter)
	mem.esc_count = C.uint8_t(t.EscCount)
	mem.esc_connectiontype = C.uint8_t(t.EscConnectiontype)
	mem.esc_online_flags = C.uint8_t(t.EscOnlineFlags)
	mem.esc_armed_flags = C.uint8_t(t.EscArmedFlags)
	EscReport__Array_to_C(mem.esc[:], t.Esc[:])
	return unsafe.Pointer(mem)
}
func (t *EscStatus) AsGoStruct(ros2_message_buffer unsafe.Pointer) {
	mem := (*C.px4_msgs__msg__EscStatus)(ros2_message_buffer)
	t.Timestamp = uint64(mem.timestamp)
	t.Counter = uint16(mem.counter)
	t.EscCount = uint8(mem.esc_count)
	t.EscConnectiontype = uint8(mem.esc_connectiontype)
	t.EscOnlineFlags = uint8(mem.esc_online_flags)
	t.EscArmedFlags = uint8(mem.esc_armed_flags)
	EscReport__Array_to_Go(t.Esc[:], mem.esc[:])
}
func (t *EscStatus) Clone() ros2types.ROS2Msg {
	clone := *t
	return &clone
}

type CEscStatus = C.px4_msgs__msg__EscStatus
type CEscStatus__Sequence = C.px4_msgs__msg__EscStatus__Sequence

func EscStatus__Sequence_to_Go(goSlice *[]EscStatus, cSlice CEscStatus__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]EscStatus, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.px4_msgs__msg__EscStatus__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_px4_msgs__msg__EscStatus * uintptr(i)),
		))
		(*goSlice)[i] = EscStatus{}
		(*goSlice)[i].AsGoStruct(unsafe.Pointer(cIdx))
	}
}
func EscStatus__Sequence_to_C(cSlice *CEscStatus__Sequence, goSlice []EscStatus) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.px4_msgs__msg__EscStatus)(C.malloc((C.size_t)(C.sizeof_struct_px4_msgs__msg__EscStatus * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.px4_msgs__msg__EscStatus)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_px4_msgs__msg__EscStatus * uintptr(i)),
		))
		*cIdx = *(*C.px4_msgs__msg__EscStatus)(v.AsCStruct())
	}
}
func EscStatus__Array_to_Go(goSlice []EscStatus, cSlice []CEscStatus) {
	for i := 0; i < len(cSlice); i++ {
		goSlice[i].AsGoStruct(unsafe.Pointer(&cSlice[i]))
	}
}
func EscStatus__Array_to_C(cSlice []CEscStatus, goSlice []EscStatus) {
	for i := 0; i < len(goSlice); i++ {
		cSlice[i] = *(*C.px4_msgs__msg__EscStatus)(goSlice[i].AsCStruct())
	}
}


