/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package px4_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/ros2/ros2types"
	"github.com/tiiuae/rclgo/pkg/ros2/ros2_type_dispatcher"
	rosidl_runtime_c "github.com/tiiuae/rclgo/pkg/ros2/rosidl_runtime_c"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lpx4_msgs__rosidl_typesupport_c -lpx4_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <px4_msgs/msg/gimbal_manager_set_attitude.h>

*/
import "C"

func init() {
	ros2_type_dispatcher.RegisterROS2MsgTypeNameAlias("px4_msgs/GimbalManagerSetAttitude", &GimbalManagerSetAttitude{})
}
const (
	GimbalManagerSetAttitude_GIMBAL_MANAGER_FLAGS_RETRACT uint32 = 1
	GimbalManagerSetAttitude_GIMBAL_MANAGER_FLAGS_NEUTRAL uint32 = 2
	GimbalManagerSetAttitude_GIMBAL_MANAGER_FLAGS_ROLL_LOCK uint32 = 4
	GimbalManagerSetAttitude_GIMBAL_MANAGER_FLAGS_PITCH_LOCK uint32 = 8
	GimbalManagerSetAttitude_GIMBAL_MANAGER_FLAGS_YAW_LOCK uint32 = 16
)

// Do not create instances of this type directly. Always use NewGimbalManagerSetAttitude
// function instead.
type GimbalManagerSetAttitude struct {
	Timestamp uint64 `yaml:"timestamp"`// time since system start (microseconds)
	OriginSysid uint8 `yaml:"origin_sysid"`
	OriginCompid uint8 `yaml:"origin_compid"`
	TargetSystem uint8 `yaml:"target_system"`
	TargetComponent uint8 `yaml:"target_component"`
	Flags uint32 `yaml:"flags"`
	GimbalDeviceId uint8 `yaml:"gimbal_device_id"`
	Q [4]float32 `yaml:"q"`
	AngularVelocityX float32 `yaml:"angular_velocity_x"`
	AngularVelocityY float32 `yaml:"angular_velocity_y"`
	AngularVelocityZ float32 `yaml:"angular_velocity_z"`
}

// NewGimbalManagerSetAttitude creates a new GimbalManagerSetAttitude with default values.
func NewGimbalManagerSetAttitude() *GimbalManagerSetAttitude {
	self := GimbalManagerSetAttitude{}
	self.SetDefaults(nil)
	return &self
}

func (t *GimbalManagerSetAttitude) SetDefaults(d interface{}) ros2types.ROS2Msg {
	
	return t
}

func (t *GimbalManagerSetAttitude) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__px4_msgs__msg__GimbalManagerSetAttitude())
}
func (t *GimbalManagerSetAttitude) PrepareMemory() unsafe.Pointer { //returns *C.px4_msgs__msg__GimbalManagerSetAttitude
	return (unsafe.Pointer)(C.px4_msgs__msg__GimbalManagerSetAttitude__create())
}
func (t *GimbalManagerSetAttitude) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.px4_msgs__msg__GimbalManagerSetAttitude__destroy((*C.px4_msgs__msg__GimbalManagerSetAttitude)(pointer_to_free))
}
func (t *GimbalManagerSetAttitude) AsCStruct() unsafe.Pointer {
	mem := (*C.px4_msgs__msg__GimbalManagerSetAttitude)(t.PrepareMemory())
	mem.timestamp = C.uint64_t(t.Timestamp)
	mem.origin_sysid = C.uint8_t(t.OriginSysid)
	mem.origin_compid = C.uint8_t(t.OriginCompid)
	mem.target_system = C.uint8_t(t.TargetSystem)
	mem.target_component = C.uint8_t(t.TargetComponent)
	mem.flags = C.uint32_t(t.Flags)
	mem.gimbal_device_id = C.uint8_t(t.GimbalDeviceId)
	cSlice_q := mem.q[:]
	rosidl_runtime_c.Float32__Array_to_C(*(*[]rosidl_runtime_c.CFloat32)(unsafe.Pointer(&cSlice_q)), t.Q[:])
	mem.angular_velocity_x = C.float(t.AngularVelocityX)
	mem.angular_velocity_y = C.float(t.AngularVelocityY)
	mem.angular_velocity_z = C.float(t.AngularVelocityZ)
	return unsafe.Pointer(mem)
}
func (t *GimbalManagerSetAttitude) AsGoStruct(ros2_message_buffer unsafe.Pointer) {
	mem := (*C.px4_msgs__msg__GimbalManagerSetAttitude)(ros2_message_buffer)
	t.Timestamp = uint64(mem.timestamp)
	t.OriginSysid = uint8(mem.origin_sysid)
	t.OriginCompid = uint8(mem.origin_compid)
	t.TargetSystem = uint8(mem.target_system)
	t.TargetComponent = uint8(mem.target_component)
	t.Flags = uint32(mem.flags)
	t.GimbalDeviceId = uint8(mem.gimbal_device_id)
	cSlice_q := mem.q[:]
	rosidl_runtime_c.Float32__Array_to_Go(t.Q[:], *(*[]rosidl_runtime_c.CFloat32)(unsafe.Pointer(&cSlice_q)))
	t.AngularVelocityX = float32(mem.angular_velocity_x)
	t.AngularVelocityY = float32(mem.angular_velocity_y)
	t.AngularVelocityZ = float32(mem.angular_velocity_z)
}
func (t *GimbalManagerSetAttitude) Clone() ros2types.ROS2Msg {
	clone := *t
	return &clone
}

type CGimbalManagerSetAttitude = C.px4_msgs__msg__GimbalManagerSetAttitude
type CGimbalManagerSetAttitude__Sequence = C.px4_msgs__msg__GimbalManagerSetAttitude__Sequence

func GimbalManagerSetAttitude__Sequence_to_Go(goSlice *[]GimbalManagerSetAttitude, cSlice CGimbalManagerSetAttitude__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GimbalManagerSetAttitude, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.px4_msgs__msg__GimbalManagerSetAttitude__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_px4_msgs__msg__GimbalManagerSetAttitude * uintptr(i)),
		))
		(*goSlice)[i] = GimbalManagerSetAttitude{}
		(*goSlice)[i].AsGoStruct(unsafe.Pointer(cIdx))
	}
}
func GimbalManagerSetAttitude__Sequence_to_C(cSlice *CGimbalManagerSetAttitude__Sequence, goSlice []GimbalManagerSetAttitude) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.px4_msgs__msg__GimbalManagerSetAttitude)(C.malloc((C.size_t)(C.sizeof_struct_px4_msgs__msg__GimbalManagerSetAttitude * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.px4_msgs__msg__GimbalManagerSetAttitude)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_px4_msgs__msg__GimbalManagerSetAttitude * uintptr(i)),
		))
		*cIdx = *(*C.px4_msgs__msg__GimbalManagerSetAttitude)(v.AsCStruct())
	}
}
func GimbalManagerSetAttitude__Array_to_Go(goSlice []GimbalManagerSetAttitude, cSlice []CGimbalManagerSetAttitude) {
	for i := 0; i < len(cSlice); i++ {
		goSlice[i].AsGoStruct(unsafe.Pointer(&cSlice[i]))
	}
}
func GimbalManagerSetAttitude__Array_to_C(cSlice []CGimbalManagerSetAttitude, goSlice []GimbalManagerSetAttitude) {
	for i := 0; i < len(goSlice); i++ {
		cSlice[i] = *(*C.px4_msgs__msg__GimbalManagerSetAttitude)(goSlice[i].AsCStruct())
	}
}


