/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package px4_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/ros2/ros2types"
	"github.com/tiiuae/rclgo/pkg/ros2/ros2_type_dispatcher"
	rosidl_runtime_c "github.com/tiiuae/rclgo/pkg/ros2/rosidl_runtime_c"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lpx4_msgs__rosidl_typesupport_c -lpx4_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <px4_msgs/msg/mavlink_log.h>

*/
import "C"

func init() {
	ros2_type_dispatcher.RegisterROS2MsgTypeNameAlias("px4_msgs/MavlinkLog", &MavlinkLog{})
}
const (
	MavlinkLog_ORB_QUEUE_LENGTH uint8 = 8
)

// Do not create instances of this type directly. Always use NewMavlinkLog
// function instead.
type MavlinkLog struct {
	Timestamp uint64 `yaml:"timestamp"`// time since system start (microseconds)
	Text [127]byte `yaml:"text"`
	Severity uint8 `yaml:"severity"`// log level (same as in the linux kernel, starting with 0)
}

// NewMavlinkLog creates a new MavlinkLog with default values.
func NewMavlinkLog() *MavlinkLog {
	self := MavlinkLog{}
	self.SetDefaults(nil)
	return &self
}

func (t *MavlinkLog) SetDefaults(d interface{}) ros2types.ROS2Msg {
	
	return t
}

func (t *MavlinkLog) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__px4_msgs__msg__MavlinkLog())
}
func (t *MavlinkLog) PrepareMemory() unsafe.Pointer { //returns *C.px4_msgs__msg__MavlinkLog
	return (unsafe.Pointer)(C.px4_msgs__msg__MavlinkLog__create())
}
func (t *MavlinkLog) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.px4_msgs__msg__MavlinkLog__destroy((*C.px4_msgs__msg__MavlinkLog)(pointer_to_free))
}
func (t *MavlinkLog) AsCStruct() unsafe.Pointer {
	mem := (*C.px4_msgs__msg__MavlinkLog)(t.PrepareMemory())
	mem.timestamp = C.uint64_t(t.Timestamp)
	cSlice_text := mem.text[:]
	rosidl_runtime_c.Char__Array_to_C(*(*[]rosidl_runtime_c.CChar)(unsafe.Pointer(&cSlice_text)), t.Text[:])
	mem.severity = C.uint8_t(t.Severity)
	return unsafe.Pointer(mem)
}
func (t *MavlinkLog) AsGoStruct(ros2_message_buffer unsafe.Pointer) {
	mem := (*C.px4_msgs__msg__MavlinkLog)(ros2_message_buffer)
	t.Timestamp = uint64(mem.timestamp)
	cSlice_text := mem.text[:]
	rosidl_runtime_c.Char__Array_to_Go(t.Text[:], *(*[]rosidl_runtime_c.CChar)(unsafe.Pointer(&cSlice_text)))
	t.Severity = uint8(mem.severity)
}
func (t *MavlinkLog) Clone() ros2types.ROS2Msg {
	clone := *t
	return &clone
}

type CMavlinkLog = C.px4_msgs__msg__MavlinkLog
type CMavlinkLog__Sequence = C.px4_msgs__msg__MavlinkLog__Sequence

func MavlinkLog__Sequence_to_Go(goSlice *[]MavlinkLog, cSlice CMavlinkLog__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]MavlinkLog, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.px4_msgs__msg__MavlinkLog__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_px4_msgs__msg__MavlinkLog * uintptr(i)),
		))
		(*goSlice)[i] = MavlinkLog{}
		(*goSlice)[i].AsGoStruct(unsafe.Pointer(cIdx))
	}
}
func MavlinkLog__Sequence_to_C(cSlice *CMavlinkLog__Sequence, goSlice []MavlinkLog) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.px4_msgs__msg__MavlinkLog)(C.malloc((C.size_t)(C.sizeof_struct_px4_msgs__msg__MavlinkLog * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.px4_msgs__msg__MavlinkLog)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_px4_msgs__msg__MavlinkLog * uintptr(i)),
		))
		*cIdx = *(*C.px4_msgs__msg__MavlinkLog)(v.AsCStruct())
	}
}
func MavlinkLog__Array_to_Go(goSlice []MavlinkLog, cSlice []CMavlinkLog) {
	for i := 0; i < len(cSlice); i++ {
		goSlice[i].AsGoStruct(unsafe.Pointer(&cSlice[i]))
	}
}
func MavlinkLog__Array_to_C(cSlice []CMavlinkLog, goSlice []MavlinkLog) {
	for i := 0; i < len(goSlice); i++ {
		cSlice[i] = *(*C.px4_msgs__msg__MavlinkLog)(goSlice[i].AsCStruct())
	}
}


