/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package px4_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/ros2/ros2types"
	"github.com/tiiuae/rclgo/pkg/ros2/ros2_type_dispatcher"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lpx4_msgs__rosidl_typesupport_c -lpx4_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <px4_msgs/msg/radio_status.h>

*/
import "C"

func init() {
	ros2_type_dispatcher.RegisterROS2MsgTypeNameAlias("px4_msgs/RadioStatus", &RadioStatus{})
}

// Do not create instances of this type directly. Always use NewRadioStatus
// function instead.
type RadioStatus struct {
	Timestamp uint64 `yaml:"timestamp"`// time since system start (microseconds)
	Rssi uint8 `yaml:"rssi"`// local signal strength
	RemoteRssi uint8 `yaml:"remote_rssi"`// remote signal strength
	Txbuf uint8 `yaml:"txbuf"`// how full the tx buffer is as a percentage
	Noise uint8 `yaml:"noise"`// background noise level
	RemoteNoise uint8 `yaml:"remote_noise"`// remote background noise level
	Rxerrors uint16 `yaml:"rxerrors"`// receive errors
	Fix uint16 `yaml:"fix"`// count of error corrected packets
}

// NewRadioStatus creates a new RadioStatus with default values.
func NewRadioStatus() *RadioStatus {
	self := RadioStatus{}
	self.SetDefaults(nil)
	return &self
}

func (t *RadioStatus) SetDefaults(d interface{}) ros2types.ROS2Msg {
	
	return t
}

func (t *RadioStatus) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__px4_msgs__msg__RadioStatus())
}
func (t *RadioStatus) PrepareMemory() unsafe.Pointer { //returns *C.px4_msgs__msg__RadioStatus
	return (unsafe.Pointer)(C.px4_msgs__msg__RadioStatus__create())
}
func (t *RadioStatus) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.px4_msgs__msg__RadioStatus__destroy((*C.px4_msgs__msg__RadioStatus)(pointer_to_free))
}
func (t *RadioStatus) AsCStruct() unsafe.Pointer {
	mem := (*C.px4_msgs__msg__RadioStatus)(t.PrepareMemory())
	mem.timestamp = C.uint64_t(t.Timestamp)
	mem.rssi = C.uint8_t(t.Rssi)
	mem.remote_rssi = C.uint8_t(t.RemoteRssi)
	mem.txbuf = C.uint8_t(t.Txbuf)
	mem.noise = C.uint8_t(t.Noise)
	mem.remote_noise = C.uint8_t(t.RemoteNoise)
	mem.rxerrors = C.uint16_t(t.Rxerrors)
	mem.fix = C.uint16_t(t.Fix)
	return unsafe.Pointer(mem)
}
func (t *RadioStatus) AsGoStruct(ros2_message_buffer unsafe.Pointer) {
	mem := (*C.px4_msgs__msg__RadioStatus)(ros2_message_buffer)
	t.Timestamp = uint64(mem.timestamp)
	t.Rssi = uint8(mem.rssi)
	t.RemoteRssi = uint8(mem.remote_rssi)
	t.Txbuf = uint8(mem.txbuf)
	t.Noise = uint8(mem.noise)
	t.RemoteNoise = uint8(mem.remote_noise)
	t.Rxerrors = uint16(mem.rxerrors)
	t.Fix = uint16(mem.fix)
}
func (t *RadioStatus) Clone() ros2types.ROS2Msg {
	clone := *t
	return &clone
}

type CRadioStatus = C.px4_msgs__msg__RadioStatus
type CRadioStatus__Sequence = C.px4_msgs__msg__RadioStatus__Sequence

func RadioStatus__Sequence_to_Go(goSlice *[]RadioStatus, cSlice CRadioStatus__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]RadioStatus, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.px4_msgs__msg__RadioStatus__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_px4_msgs__msg__RadioStatus * uintptr(i)),
		))
		(*goSlice)[i] = RadioStatus{}
		(*goSlice)[i].AsGoStruct(unsafe.Pointer(cIdx))
	}
}
func RadioStatus__Sequence_to_C(cSlice *CRadioStatus__Sequence, goSlice []RadioStatus) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.px4_msgs__msg__RadioStatus)(C.malloc((C.size_t)(C.sizeof_struct_px4_msgs__msg__RadioStatus * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.px4_msgs__msg__RadioStatus)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_px4_msgs__msg__RadioStatus * uintptr(i)),
		))
		*cIdx = *(*C.px4_msgs__msg__RadioStatus)(v.AsCStruct())
	}
}
func RadioStatus__Array_to_Go(goSlice []RadioStatus, cSlice []CRadioStatus) {
	for i := 0; i < len(cSlice); i++ {
		goSlice[i].AsGoStruct(unsafe.Pointer(&cSlice[i]))
	}
}
func RadioStatus__Array_to_C(cSlice []CRadioStatus, goSlice []RadioStatus) {
	for i := 0; i < len(goSlice); i++ {
		cSlice[i] = *(*C.px4_msgs__msg__RadioStatus)(goSlice[i].AsCStruct())
	}
}


