/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package px4_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/ros2/types"
	"github.com/tiiuae/rclgo/pkg/ros2/ros2_type_dispatcher"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lpx4_msgs__rosidl_typesupport_c -lpx4_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <px4_msgs/msg/rtl_flight_time.h>

*/
import "C"

func init() {
	ros2_type_dispatcher.RegisterROS2MsgTypeNameAlias("px4_msgs/RtlFlightTime", RtlFlightTimeTypeSupport)
}

// Do not create instances of this type directly. Always use NewRtlFlightTime
// function instead.
type RtlFlightTime struct {
	Timestamp uint64 `yaml:"timestamp"`// time since system start (microseconds)
	RtlTimeS float32 `yaml:"rtl_time_s"`// how long in seconds will the RTL take
	RtlLimitFraction float32 `yaml:"rtl_limit_fraction"`// what fraction of the allowable RTL time would be taken
}

// NewRtlFlightTime creates a new RtlFlightTime with default values.
func NewRtlFlightTime() *RtlFlightTime {
	self := RtlFlightTime{}
	self.SetDefaults()
	return &self
}

func (t *RtlFlightTime) Clone() types.Message {
	clone := *t
	return &clone
}

func (t *RtlFlightTime) SetDefaults() {
	
}

// Modifying this variable is undefined behavior.
var RtlFlightTimeTypeSupport types.MessageTypeSupport = _RtlFlightTimeTypeSupport{}

type _RtlFlightTimeTypeSupport struct{}

func (t _RtlFlightTimeTypeSupport) New() types.Message {
	return NewRtlFlightTime()
}

func (t _RtlFlightTimeTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.px4_msgs__msg__RtlFlightTime
	return (unsafe.Pointer)(C.px4_msgs__msg__RtlFlightTime__create())
}

func (t _RtlFlightTimeTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.px4_msgs__msg__RtlFlightTime__destroy((*C.px4_msgs__msg__RtlFlightTime)(pointer_to_free))
}

func (t _RtlFlightTimeTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*RtlFlightTime)
	mem := (*C.px4_msgs__msg__RtlFlightTime)(dst)
	mem.timestamp = C.uint64_t(m.Timestamp)
	mem.rtl_time_s = C.float(m.RtlTimeS)
	mem.rtl_limit_fraction = C.float(m.RtlLimitFraction)
}

func (t _RtlFlightTimeTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*RtlFlightTime)
	mem := (*C.px4_msgs__msg__RtlFlightTime)(ros2_message_buffer)
	m.Timestamp = uint64(mem.timestamp)
	m.RtlTimeS = float32(mem.rtl_time_s)
	m.RtlLimitFraction = float32(mem.rtl_limit_fraction)
}

func (t _RtlFlightTimeTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__px4_msgs__msg__RtlFlightTime())
}

type CRtlFlightTime = C.px4_msgs__msg__RtlFlightTime
type CRtlFlightTime__Sequence = C.px4_msgs__msg__RtlFlightTime__Sequence

func RtlFlightTime__Sequence_to_Go(goSlice *[]RtlFlightTime, cSlice CRtlFlightTime__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]RtlFlightTime, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.px4_msgs__msg__RtlFlightTime__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_px4_msgs__msg__RtlFlightTime * uintptr(i)),
		))
		RtlFlightTimeTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func RtlFlightTime__Sequence_to_C(cSlice *CRtlFlightTime__Sequence, goSlice []RtlFlightTime) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.px4_msgs__msg__RtlFlightTime)(C.malloc((C.size_t)(C.sizeof_struct_px4_msgs__msg__RtlFlightTime * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.px4_msgs__msg__RtlFlightTime)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_px4_msgs__msg__RtlFlightTime * uintptr(i)),
		))
		RtlFlightTimeTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func RtlFlightTime__Array_to_Go(goSlice []RtlFlightTime, cSlice []CRtlFlightTime) {
	for i := 0; i < len(cSlice); i++ {
		RtlFlightTimeTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func RtlFlightTime__Array_to_C(cSlice []CRtlFlightTime, goSlice []RtlFlightTime) {
	for i := 0; i < len(goSlice); i++ {
		RtlFlightTimeTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
