/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package visualization_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/ros2/ros2types"
	"github.com/tiiuae/rclgo/pkg/ros2/ros2_type_dispatcher"
	rosidl_runtime_c "github.com/tiiuae/rclgo/pkg/ros2/rosidl_runtime_c"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lvisualization_msgs__rosidl_typesupport_c -lvisualization_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <visualization_msgs/msg/interactive_marker_update.h>

*/
import "C"

func init() {
	ros2_type_dispatcher.RegisterROS2MsgTypeNameAlias("visualization_msgs/InteractiveMarkerUpdate", &InteractiveMarkerUpdate{})
}
const (
	InteractiveMarkerUpdate_KEEP_ALIVE uint8 = 0// Type holds the purpose of this message.  It must be one of UPDATE or KEEP_ALIVE.UPDATE: Incremental update to previous state.The sequence number must be 1 higher than forthe previous update.KEEP_ALIVE: Indicates the that the server is still living.The sequence number does not increase.No payload data should be filled out (markers, poses, or erases).
	InteractiveMarkerUpdate_UPDATE uint8 = 1// Type holds the purpose of this message.  It must be one of UPDATE or KEEP_ALIVE.UPDATE: Incremental update to previous state.The sequence number must be 1 higher than forthe previous update.KEEP_ALIVE: Indicates the that the server is still living.The sequence number does not increase.No payload data should be filled out (markers, poses, or erases).
)

// Do not create instances of this type directly. Always use NewInteractiveMarkerUpdate
// function instead.
type InteractiveMarkerUpdate struct {
	ServerId rosidl_runtime_c.String `yaml:"server_id"`// Identifying string. Must be unique in the topic namespacethat this server works on.
	SeqNum uint64 `yaml:"seq_num"`// Sequence number.The client will use this to detect if it has missed an update.
	Type uint8 `yaml:"type"`
	Markers []InteractiveMarker `yaml:"markers"`// Markers to be added or updated
	Poses []InteractiveMarkerPose `yaml:"poses"`// Poses of markers that should be moved
	Erases []rosidl_runtime_c.String `yaml:"erases"`// Names of markers to be erased
}

// NewInteractiveMarkerUpdate creates a new InteractiveMarkerUpdate with default values.
func NewInteractiveMarkerUpdate() *InteractiveMarkerUpdate {
	self := InteractiveMarkerUpdate{}
	self.SetDefaults(nil)
	return &self
}

func (t *InteractiveMarkerUpdate) SetDefaults(d interface{}) ros2types.ROS2Msg {
	t.ServerId.SetDefaults("")
	
	return t
}

func (t *InteractiveMarkerUpdate) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__visualization_msgs__msg__InteractiveMarkerUpdate())
}
func (t *InteractiveMarkerUpdate) PrepareMemory() unsafe.Pointer { //returns *C.visualization_msgs__msg__InteractiveMarkerUpdate
	return (unsafe.Pointer)(C.visualization_msgs__msg__InteractiveMarkerUpdate__create())
}
func (t *InteractiveMarkerUpdate) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.visualization_msgs__msg__InteractiveMarkerUpdate__destroy((*C.visualization_msgs__msg__InteractiveMarkerUpdate)(pointer_to_free))
}
func (t *InteractiveMarkerUpdate) AsCStruct() unsafe.Pointer {
	mem := (*C.visualization_msgs__msg__InteractiveMarkerUpdate)(t.PrepareMemory())
	mem.server_id = *(*C.rosidl_runtime_c__String)(t.ServerId.AsCStruct())
	mem.seq_num = C.uint64_t(t.SeqNum)
	mem._type = C.uint8_t(t.Type)
	InteractiveMarker__Sequence_to_C(&mem.markers, t.Markers)
	InteractiveMarkerPose__Sequence_to_C(&mem.poses, t.Poses)
	rosidl_runtime_c.String__Sequence_to_C((*rosidl_runtime_c.CString__Sequence)(unsafe.Pointer(&mem.erases)), t.Erases)
	return unsafe.Pointer(mem)
}
func (t *InteractiveMarkerUpdate) AsGoStruct(ros2_message_buffer unsafe.Pointer) {
	mem := (*C.visualization_msgs__msg__InteractiveMarkerUpdate)(ros2_message_buffer)
	t.ServerId.AsGoStruct(unsafe.Pointer(&mem.server_id))
	t.SeqNum = uint64(mem.seq_num)
	t.Type = uint8(mem._type)
	InteractiveMarker__Sequence_to_Go(&t.Markers, mem.markers)
	InteractiveMarkerPose__Sequence_to_Go(&t.Poses, mem.poses)
	rosidl_runtime_c.String__Sequence_to_Go(&t.Erases, *(*rosidl_runtime_c.CString__Sequence)(unsafe.Pointer(&mem.erases)))
}
func (t *InteractiveMarkerUpdate) Clone() ros2types.ROS2Msg {
	clone := *t
	return &clone
}

type CInteractiveMarkerUpdate = C.visualization_msgs__msg__InteractiveMarkerUpdate
type CInteractiveMarkerUpdate__Sequence = C.visualization_msgs__msg__InteractiveMarkerUpdate__Sequence

func InteractiveMarkerUpdate__Sequence_to_Go(goSlice *[]InteractiveMarkerUpdate, cSlice CInteractiveMarkerUpdate__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]InteractiveMarkerUpdate, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.visualization_msgs__msg__InteractiveMarkerUpdate__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_visualization_msgs__msg__InteractiveMarkerUpdate * uintptr(i)),
		))
		(*goSlice)[i] = InteractiveMarkerUpdate{}
		(*goSlice)[i].AsGoStruct(unsafe.Pointer(cIdx))
	}
}
func InteractiveMarkerUpdate__Sequence_to_C(cSlice *CInteractiveMarkerUpdate__Sequence, goSlice []InteractiveMarkerUpdate) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.visualization_msgs__msg__InteractiveMarkerUpdate)(C.malloc((C.size_t)(C.sizeof_struct_visualization_msgs__msg__InteractiveMarkerUpdate * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.visualization_msgs__msg__InteractiveMarkerUpdate)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_visualization_msgs__msg__InteractiveMarkerUpdate * uintptr(i)),
		))
		*cIdx = *(*C.visualization_msgs__msg__InteractiveMarkerUpdate)(v.AsCStruct())
	}
}
func InteractiveMarkerUpdate__Array_to_Go(goSlice []InteractiveMarkerUpdate, cSlice []CInteractiveMarkerUpdate) {
	for i := 0; i < len(cSlice); i++ {
		goSlice[i].AsGoStruct(unsafe.Pointer(&cSlice[i]))
	}
}
func InteractiveMarkerUpdate__Array_to_C(cSlice []CInteractiveMarkerUpdate, goSlice []InteractiveMarkerUpdate) {
	for i := 0; i < len(goSlice); i++ {
		cSlice[i] = *(*C.visualization_msgs__msg__InteractiveMarkerUpdate)(goSlice[i].AsCStruct())
	}
}


