/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package px4_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lpx4_msgs__rosidl_typesupport_c -lpx4_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <px4_msgs/msg/mag_worker_data.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("px4_msgs/MagWorkerData", MagWorkerDataTypeSupport)
}
const (
	MagWorkerData_MAX_MAGS uint8 = 4
)

// Do not create instances of this type directly. Always use NewMagWorkerData
// function instead.
type MagWorkerData struct {
	Timestamp uint64 `yaml:"timestamp"`// time since system start (microseconds)
	TimestampSample uint64 `yaml:"timestamp_sample"`
	DoneCount uint32 `yaml:"done_count"`
	CalibrationPointsPerside uint32 `yaml:"calibration_points_perside"`
	CalibrationIntervalPersideUs uint64 `yaml:"calibration_interval_perside_us"`
	CalibrationCounterTotal [4]uint32 `yaml:"calibration_counter_total"`
	SideDataCollected [4]bool `yaml:"side_data_collected"`
	X [4]float32 `yaml:"x"`
	Y [4]float32 `yaml:"y"`
	Z [4]float32 `yaml:"z"`
}

// NewMagWorkerData creates a new MagWorkerData with default values.
func NewMagWorkerData() *MagWorkerData {
	self := MagWorkerData{}
	self.SetDefaults()
	return &self
}

func (t *MagWorkerData) Clone() types.Message {
	clone := *t
	return &clone
}

func (t *MagWorkerData) SetDefaults() {
	
}

// Modifying this variable is undefined behavior.
var MagWorkerDataTypeSupport types.MessageTypeSupport = _MagWorkerDataTypeSupport{}

type _MagWorkerDataTypeSupport struct{}

func (t _MagWorkerDataTypeSupport) New() types.Message {
	return NewMagWorkerData()
}

func (t _MagWorkerDataTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.px4_msgs__msg__MagWorkerData
	return (unsafe.Pointer)(C.px4_msgs__msg__MagWorkerData__create())
}

func (t _MagWorkerDataTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.px4_msgs__msg__MagWorkerData__destroy((*C.px4_msgs__msg__MagWorkerData)(pointer_to_free))
}

func (t _MagWorkerDataTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*MagWorkerData)
	mem := (*C.px4_msgs__msg__MagWorkerData)(dst)
	mem.timestamp = C.uint64_t(m.Timestamp)
	mem.timestamp_sample = C.uint64_t(m.TimestampSample)
	mem.done_count = C.uint32_t(m.DoneCount)
	mem.calibration_points_perside = C.uint32_t(m.CalibrationPointsPerside)
	mem.calibration_interval_perside_us = C.uint64_t(m.CalibrationIntervalPersideUs)
	cSlice_calibration_counter_total := mem.calibration_counter_total[:]
	primitives.Uint32__Array_to_C(*(*[]primitives.CUint32)(unsafe.Pointer(&cSlice_calibration_counter_total)), m.CalibrationCounterTotal[:])
	cSlice_side_data_collected := mem.side_data_collected[:]
	primitives.Bool__Array_to_C(*(*[]primitives.CBool)(unsafe.Pointer(&cSlice_side_data_collected)), m.SideDataCollected[:])
	cSlice_x := mem.x[:]
	primitives.Float32__Array_to_C(*(*[]primitives.CFloat32)(unsafe.Pointer(&cSlice_x)), m.X[:])
	cSlice_y := mem.y[:]
	primitives.Float32__Array_to_C(*(*[]primitives.CFloat32)(unsafe.Pointer(&cSlice_y)), m.Y[:])
	cSlice_z := mem.z[:]
	primitives.Float32__Array_to_C(*(*[]primitives.CFloat32)(unsafe.Pointer(&cSlice_z)), m.Z[:])
}

func (t _MagWorkerDataTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*MagWorkerData)
	mem := (*C.px4_msgs__msg__MagWorkerData)(ros2_message_buffer)
	m.Timestamp = uint64(mem.timestamp)
	m.TimestampSample = uint64(mem.timestamp_sample)
	m.DoneCount = uint32(mem.done_count)
	m.CalibrationPointsPerside = uint32(mem.calibration_points_perside)
	m.CalibrationIntervalPersideUs = uint64(mem.calibration_interval_perside_us)
	cSlice_calibration_counter_total := mem.calibration_counter_total[:]
	primitives.Uint32__Array_to_Go(m.CalibrationCounterTotal[:], *(*[]primitives.CUint32)(unsafe.Pointer(&cSlice_calibration_counter_total)))
	cSlice_side_data_collected := mem.side_data_collected[:]
	primitives.Bool__Array_to_Go(m.SideDataCollected[:], *(*[]primitives.CBool)(unsafe.Pointer(&cSlice_side_data_collected)))
	cSlice_x := mem.x[:]
	primitives.Float32__Array_to_Go(m.X[:], *(*[]primitives.CFloat32)(unsafe.Pointer(&cSlice_x)))
	cSlice_y := mem.y[:]
	primitives.Float32__Array_to_Go(m.Y[:], *(*[]primitives.CFloat32)(unsafe.Pointer(&cSlice_y)))
	cSlice_z := mem.z[:]
	primitives.Float32__Array_to_Go(m.Z[:], *(*[]primitives.CFloat32)(unsafe.Pointer(&cSlice_z)))
}

func (t _MagWorkerDataTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__px4_msgs__msg__MagWorkerData())
}

type CMagWorkerData = C.px4_msgs__msg__MagWorkerData
type CMagWorkerData__Sequence = C.px4_msgs__msg__MagWorkerData__Sequence

func MagWorkerData__Sequence_to_Go(goSlice *[]MagWorkerData, cSlice CMagWorkerData__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]MagWorkerData, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.px4_msgs__msg__MagWorkerData__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_px4_msgs__msg__MagWorkerData * uintptr(i)),
		))
		MagWorkerDataTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func MagWorkerData__Sequence_to_C(cSlice *CMagWorkerData__Sequence, goSlice []MagWorkerData) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.px4_msgs__msg__MagWorkerData)(C.malloc((C.size_t)(C.sizeof_struct_px4_msgs__msg__MagWorkerData * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.px4_msgs__msg__MagWorkerData)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_px4_msgs__msg__MagWorkerData * uintptr(i)),
		))
		MagWorkerDataTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func MagWorkerData__Array_to_Go(goSlice []MagWorkerData, cSlice []CMagWorkerData) {
	for i := 0; i < len(cSlice); i++ {
		MagWorkerDataTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func MagWorkerData__Array_to_C(cSlice []CMagWorkerData, goSlice []MagWorkerData) {
	for i := 0; i < len(goSlice); i++ {
		MagWorkerDataTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
