/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package px4_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lpx4_msgs__rosidl_typesupport_c -lpx4_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <px4_msgs/msg/pwm_input.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("px4_msgs/PwmInput", PwmInputTypeSupport)
}

// Do not create instances of this type directly. Always use NewPwmInput
// function instead.
type PwmInput struct {
	Timestamp uint64 `yaml:"timestamp"`// Time since system start (microseconds)
	ErrorCount uint64 `yaml:"error_count"`// Timer overcapture error flag (AUX5 or MAIN5)
	PulseWidth uint32 `yaml:"pulse_width"`// Pulse width, timer counts
	Period uint32 `yaml:"period"`// Period, timer counts
}

// NewPwmInput creates a new PwmInput with default values.
func NewPwmInput() *PwmInput {
	self := PwmInput{}
	self.SetDefaults()
	return &self
}

func (t *PwmInput) Clone() types.Message {
	clone := *t
	return &clone
}

func (t *PwmInput) SetDefaults() {
	
}

// Modifying this variable is undefined behavior.
var PwmInputTypeSupport types.MessageTypeSupport = _PwmInputTypeSupport{}

type _PwmInputTypeSupport struct{}

func (t _PwmInputTypeSupport) New() types.Message {
	return NewPwmInput()
}

func (t _PwmInputTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.px4_msgs__msg__PwmInput
	return (unsafe.Pointer)(C.px4_msgs__msg__PwmInput__create())
}

func (t _PwmInputTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.px4_msgs__msg__PwmInput__destroy((*C.px4_msgs__msg__PwmInput)(pointer_to_free))
}

func (t _PwmInputTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*PwmInput)
	mem := (*C.px4_msgs__msg__PwmInput)(dst)
	mem.timestamp = C.uint64_t(m.Timestamp)
	mem.error_count = C.uint64_t(m.ErrorCount)
	mem.pulse_width = C.uint32_t(m.PulseWidth)
	mem.period = C.uint32_t(m.Period)
}

func (t _PwmInputTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*PwmInput)
	mem := (*C.px4_msgs__msg__PwmInput)(ros2_message_buffer)
	m.Timestamp = uint64(mem.timestamp)
	m.ErrorCount = uint64(mem.error_count)
	m.PulseWidth = uint32(mem.pulse_width)
	m.Period = uint32(mem.period)
}

func (t _PwmInputTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__px4_msgs__msg__PwmInput())
}

type CPwmInput = C.px4_msgs__msg__PwmInput
type CPwmInput__Sequence = C.px4_msgs__msg__PwmInput__Sequence

func PwmInput__Sequence_to_Go(goSlice *[]PwmInput, cSlice CPwmInput__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]PwmInput, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.px4_msgs__msg__PwmInput__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_px4_msgs__msg__PwmInput * uintptr(i)),
		))
		PwmInputTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func PwmInput__Sequence_to_C(cSlice *CPwmInput__Sequence, goSlice []PwmInput) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.px4_msgs__msg__PwmInput)(C.malloc((C.size_t)(C.sizeof_struct_px4_msgs__msg__PwmInput * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.px4_msgs__msg__PwmInput)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_px4_msgs__msg__PwmInput * uintptr(i)),
		))
		PwmInputTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func PwmInput__Array_to_Go(goSlice []PwmInput, cSlice []CPwmInput) {
	for i := 0; i < len(cSlice); i++ {
		PwmInputTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func PwmInput__Array_to_C(cSlice []CPwmInput, goSlice []PwmInput) {
	for i := 0; i < len(goSlice); i++ {
		PwmInputTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
