/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package lifecycle_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/foxy/lib -Wl,-rpath=/opt/ros/foxy/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -llifecycle_msgs__rosidl_typesupport_c -llifecycle_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/foxy/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <lifecycle_msgs/srv/get_available_transitions.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("lifecycle_msgs/GetAvailableTransitions_Request", GetAvailableTransitions_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewGetAvailableTransitions_Request
// function instead.
type GetAvailableTransitions_Request struct {
}

// NewGetAvailableTransitions_Request creates a new GetAvailableTransitions_Request with default values.
func NewGetAvailableTransitions_Request() *GetAvailableTransitions_Request {
	self := GetAvailableTransitions_Request{}
	self.SetDefaults()
	return &self
}

func (t *GetAvailableTransitions_Request) Clone() types.Message {
	clone := *t
	return &clone
}

func (t *GetAvailableTransitions_Request) SetDefaults() {
	
}

// Modifying this variable is undefined behavior.
var GetAvailableTransitions_RequestTypeSupport types.MessageTypeSupport = _GetAvailableTransitions_RequestTypeSupport{}

type _GetAvailableTransitions_RequestTypeSupport struct{}

func (t _GetAvailableTransitions_RequestTypeSupport) New() types.Message {
	return NewGetAvailableTransitions_Request()
}

func (t _GetAvailableTransitions_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.lifecycle_msgs__srv__GetAvailableTransitions_Request
	return (unsafe.Pointer)(C.lifecycle_msgs__srv__GetAvailableTransitions_Request__create())
}

func (t _GetAvailableTransitions_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.lifecycle_msgs__srv__GetAvailableTransitions_Request__destroy((*C.lifecycle_msgs__srv__GetAvailableTransitions_Request)(pointer_to_free))
}

func (t _GetAvailableTransitions_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _GetAvailableTransitions_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _GetAvailableTransitions_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__lifecycle_msgs__srv__GetAvailableTransitions_Request())
}

type CGetAvailableTransitions_Request = C.lifecycle_msgs__srv__GetAvailableTransitions_Request
type CGetAvailableTransitions_Request__Sequence = C.lifecycle_msgs__srv__GetAvailableTransitions_Request__Sequence

func GetAvailableTransitions_Request__Sequence_to_Go(goSlice *[]GetAvailableTransitions_Request, cSlice CGetAvailableTransitions_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetAvailableTransitions_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.lifecycle_msgs__srv__GetAvailableTransitions_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_lifecycle_msgs__srv__GetAvailableTransitions_Request * uintptr(i)),
		))
		GetAvailableTransitions_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GetAvailableTransitions_Request__Sequence_to_C(cSlice *CGetAvailableTransitions_Request__Sequence, goSlice []GetAvailableTransitions_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.lifecycle_msgs__srv__GetAvailableTransitions_Request)(C.malloc((C.size_t)(C.sizeof_struct_lifecycle_msgs__srv__GetAvailableTransitions_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.lifecycle_msgs__srv__GetAvailableTransitions_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_lifecycle_msgs__srv__GetAvailableTransitions_Request * uintptr(i)),
		))
		GetAvailableTransitions_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GetAvailableTransitions_Request__Array_to_Go(goSlice []GetAvailableTransitions_Request, cSlice []CGetAvailableTransitions_Request) {
	for i := 0; i < len(cSlice); i++ {
		GetAvailableTransitions_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetAvailableTransitions_Request__Array_to_C(cSlice []CGetAvailableTransitions_Request, goSlice []GetAvailableTransitions_Request) {
	for i := 0; i < len(goSlice); i++ {
		GetAvailableTransitions_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
